spring.datasource.url=jdbc:mysql://localhost:3306/GRAY_Hospital
spring.datasource.username=hms_user
spring.datasource.password=hms123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8008